/*
    Tubster theme ported for Ace Editor
    Ported by Chris Clower
    Twitter: @clowerweb
    Email: chris@clowerweb.com
    Website: http://clowerweb.com/

    Tubster originally created for TextMate by Filmgirl (Christina Warren)
    https://github.com/filmgirl/TextMate-Themes/blob/master/Tubster.tmTheme
*/

define("ace/theme/tubster",["require","exports","module","ace/lib/dom"],function(a,b,c){b.isDark=!0,b.cssClass="ace-tubster",b.cssText=".ace-tubster .ace_editor{border:2px solid #9f9f9f;}.ace-tubster .ace_editor.ace_focus{border:2px solid #327fbd;}.ace-tubster .ace_gutter{background:#000;color:#9B9B9B;}.ace-tubster .ace_print_margin{width:1px;background:#e8e8e8;}.ace-tubster .ace_scroller{background-color:#232323;}.ace-tubster .ace_text-layer{color:#E6E1DC;}.ace-tubster .ace_cursor{border-left:2px solid #FFF;}.ace-tubster .ace_cursor.ace_overwrite{border-left:0;border-bottom:1px solid #FFF;}.ace-tubster .ace_marker-layer .ace_selection{background:rgba(90,100,126,0.88);}.ace-tubster.multiselect .ace_selection.start{box-shadow:0 0 3px 0 #232323;border-radius:2px;}.ace-tubster .ace_marker-layer .ace_step{background:#c6dbae;}.ace-tubster .ace_marker-layer .ace_bracket{border:1px solid #404040;margin:-1px 0 0 -1px;}.ace-tubster .ace_marker-layer .ace_active_line{background:#333435;}.ace-tubster .ace_gutter_active_line{background-color:#333435;}.ace-tubster .ace_marker-layer .ace_selected_word{border:1px solid rgba(90,100,126,0.88);}.ace-tubster .ace_invisible{color:#404040;}.ace-tubster .ace_constant.ace_numeric{color:#9C6;}.ace-tubster .ace_invalid{color:#FFF;background-color:#C00;}.ace-tubster .ace_fold{background-color:#FC3;border-color:#E6E1DC;}.ace-tubster .ace_support.ace_function{color:#DA4939;}.ace-tubster .ace_comment{font-style:italic;color:#666;}.ace-tubster .ace_entity.ace_name{color:#FFF;}.ace-tubster .ace_markup.ace_underline{text-decoration:underline;}.ace-tubster .ace_keyword,.ace-tubster .ace_meta,.ace-tubster .ace_storage{color:#C63;}.ace-tubster .ace_constant,.ace-tubster .ace_constant.ace_other,.ace-tubster .ace_constant.ace_character,,.ace-tubster .ace_constant.ace_character.ace_escape,{color:#34A2D9;}.ace-tubster .ace_constant.ace_language,.ace-tubster .ace_variable.ace_language{color:#39C;}.ace-tubster .ace_support.ace_constant,.ace-tubster .ace_string{color:#9C3;}.ace-tubster .ace_variable,.ace-tubster .ace_meta.ace_tag,.ace-tubster .ace_entity.ace_other.ace_attribute-name,.ace-tubster .ace_entity.ace_name.ace_function{color:#FC3;}";var d=a("../lib/dom");d.importCssString(b.cssText,b.cssClass)});
